name: Dump Baserow tables and create ARCHE turtle files

on:
  workflow_dispatch:
    inputs:
      database_id:
        type: number
        description: '(Required) Database ID as number'
        required: true
        default: 0
      project_name:
        type: string
        description: '(Required) Project Name as string'
        required: true
        default: '' 

jobs:
  update_baserow:
    name: Uploading Arche Schema to Baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
      BASEROW_DB_ID: ${{ github.event.inputs.database_id }}
      BASEROW_USER: ${{ secrets.BASEROW_USER }}
      BASEROW_PW: ${{ secrets.BASEROW_PW }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Baserow Dump and TEI/XML Download
        run: |
          python scripts/baserow_dump.py
      - name: Creating ARCHE constants ttl file
        run: |
          python scripts/arche_constants.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Downloaded/Updated Data